backend:
  name: github
  repo: chatxbuy/chatxbuy-blog
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://auth.chatxbuy.com

media_folder: public/img
public_folder: /img

slug:
  encoding: 'unicode'
  clean_accents: false
  sanitize_replacement: '-'

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: '{{articleId}}-{{title}}'
    format: frontmatter
    editor:
      preview: false
    fields:
      - {
          label: 'Article ID',
          name: 'articleId',
          widget: 'string',
          hint: '文章 ID，用於生成 URL',
        }
      - {
        label: 'Draft',
        name: 'draft',
        widget: 'boolean',
        required: false,
        default: true,
        hint: '草稿狀態，勾選表示文章為草稿',
      }
      - { label: 'Path', name: 'path', widget: 'hidden', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Cover', name: 'cover', widget: 'image', required: false }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DDTHH:mm:ss.SSSZ',
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - {
          label: 'Pinned',
          name: 'pinned',
          widget: 'boolean',
          required: false,
          default: false,
        }
      
